export const SET_CITY_COUNTRY = 'Weather/App/SET_CITY_COUNTRY';
export const NEW_SEARCH = 'Weather/App/NEW_SEARCH';

export const START_FETCH_FORECAST_DATA = 'Weather/App/START_FETCH_FORECAST_DATA';
export const SUCCESS_FETCHED_FORECAST = 'Weather/App/SUCCESS_FETCHED_FORECAST';
export const FINISH_FETCH_FORECAST_DATA = 'Weather/App/FINISH_FETCH_FORECAST_DATA';
export const ERROR_FETCHED_FORECAST = 'Weather/App/ERROR_FETCHED_FORECAST';
